### ISSUE TITLE
Addon stops wroking in firefox 128 esr

### ISSUE THREAD

**Issue by Janaue** [Mikhail-M12/Better-FindButton#1]
Hello

I hope somebody will read this. The addon doesn't work on firefox 128 and beyond, like 130 dev edition, maybe even on 115 ESR. When the magnifier icon is press nothing happens, whereas when the addon is disabled, the usual find bar appears, but ofc clicking again on the icon does not hide the find bar...
The extension still works on firefox 109.

I verified that I have extensions.experiments.enabled=true and I installed the JS loader correctly.

**Comment by Mikhail-M12** [comment]
[Janaue](https://github.com/Janaue), thank you.
Fixed in [v1.0.128](https://github.com/Mikhail-M12/Better-FindButton/releases/tag/v1.0.128).
(r3dfox 128.2.0 — works.)
